### ISSUE TITLE
Background-colour contrast & nav:focus/hover

### ISSUE THREAD

**Issue by mato0039** [mato0039/kraken-good-accessibility#1]
Hi guys, 

I'm having trouble figuring these last three issues that Markbot wants me to fix. 

1. The contrast of the header's text with the background colour isn't enough according to Markbot - do I just change the colour of the header text? 

2. I don't understand the message about the nav:last-of-type not being found in the a:focus and a:hover states, how do I fix this?

Thanks!

@hellachella
@jessjodoin

<img width="515" alt="Screen Shot 2020-10-03 at 4 44 26 PM" src="https://user-images.githubusercontent.com/55108737/95001447-1b880900-0598-11eb-9957-dd9796ee59ef.png">

**Comment by JessJodoin** [comment]
For the contrast issue add`background-color: #1e7c74;` to both your header and footer. When using background images, you should add a background colour for accessibility reasons so when images are turned off you can still read the text.

For the nav hover issue, try adding this to the focus state `outline-offset: .1rem;`

I'm not sure if that's the fix but it might be, so try it out an let me know 😄

**Comment by mato0039** [comment]
It worked for the background colour! Thanks. 

However, I still get the same message for the nav focus and nav hover.

<img width="515" alt="Screen Shot 2020-10-04 at 11 33 19 AM" src="https://user-images.githubusercontent.com/55108737/95019800-7459af00-0635-11eb-8d08-b286161feb87.png">

@JessJodoin 
@hellachella

**Comment by JessJodoin** [comment]
Oh! I think it might be how you have your` index.html` set up for the header, so try this inside your `<main>` tag (line 17)

```
<header>
  <hgroup>
    <h1>Chapter XVIII</h1>
    <h2>The Poulps</h2>
  </hgroup>

  <nav role="navigation">
    <ul>
      <li>
        <a href="chapter-xvii.html" aria-label="Go to the previous chapter">
          <i class="icon" role="presentation"><svg><use xlink:href="images/icons.svg#prev"></use></svg></i>
        </a>
      </li>

      <li>
        <a href="contents.html" aria-label="Go to the table of contents">
          <i class="icon" role="presentation"><svg><use xlink:href="images/icons.svg#contents"></use></svg></i>
         </a>
       </li>
       
       <li>
         <a href="chapter-xix.html" aria-label="Go to the next chapter">
           <i class="icon" role="presentation"><svg><use xlink:href="images/icons.svg#next"></use></svg></i>
         </a>
        </li>
      </ul>
    </nav>
 </header>
```

**Comment by mato0039** [comment]
That was it!!! 
Thank you so much Jess! :)
